version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: contentful-rest-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contentful_rest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contentful-rest-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/contentful_rest
      - CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE_ID}
      - CONTENTFUL_ACCESS_TOKEN=${CONTENTFUL_ACCESS_TOKEN}
      - CONTENTFUL_ENVIRONMENT=${CONTENTFUL_ENVIRONMENT}
      - CONTENTFUL_CONTENT_TYPE=${CONTENTFUL_CONTENT_TYPE}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: 